# 将所有数字转为 String 类型返回，避免前端数据精度丢失的问题
jackson:
  generator:
    write-numbers-as-strings: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mybatis/mapping/*.xml

logging:
  config: classpath:logback-boot.xml

spring:
  main:
    allow-bean-definition-overriding: true

#关掉mq的健康检查，防止某些没有用到mq的服务启动报错，个别服务如需mq监控，单独开启
management:
  health:
    rabbit:
      enabled: false


